package edu.pitt.utils;

import java.util.List;

import edu.pitt.bean.Location;
import edu.pitt.bean.Visitor;

public class TravelService {
	/**
	 * To determine this location is liked by this visitor or not.
	 * @param location
	 * @param visitor
	 * @return like => true; otherwise false;
	 */
	public boolean isLike(Location location, Visitor visitor){
		List<Integer> list = Helper.LocationlikeMap.get(location.getIndex());
		for(Integer index: list){
			if(index == visitor.getIndex()){
				return true;
			}
		}
		return false;
	}
	
	/**
	 * get the result by given location and visitor
	 * @param i, the index of iteration
	 * @param location
	 * @param visitor
	 * @return a String: who did (not) like which place
	 */
	public String isLikeRes(int i, Location location, Visitor visitor){
		String ans = null;
		String people = "Visitor " + (i + 1);
		System.out.println(people + " is going to " + location.getName());
		if(isLike(location, visitor)){
			ans = people + " did like " + location.getName();
		}else{
			ans = people + " did not like " + location.getName();
		}
		return ans;
	}
	
	/**
	 * To decide whether it is time to quit
	 * @return
	 */
	public boolean quit(RandomGenerator generator){
		double seed = generator.getQuitRandom();
		if(seed < Helper.quitSeed){
			return true;
		}
		return false;
	}
	
	/**
	 * check the parameters is right or not
	 * @param args
	 * @return
	 */
	public boolean checkArgs(String[] args){
		if(args.length != 1){
			System.out.println("The program shall accept one and only one argument");
			return false;
		}
		try{
			Integer.parseInt(args[0]);
		}catch(Exception e){
			System.out.println("The input must be a Integer");
			return false;
		}
		return true;
	}
	
	/**
	 * get a certain visitor which is selected by a random number generated by RandomGenerator
	 * @param generator
	 * @return
	 * @throws Exception
	 */
	public Visitor getVisitor(RandomGenerator generator) throws Exception{
		Visitor visitior = null;
		int num = generator.getVistorRandom();
		if(num >= Helper.visitorsNum){
			throw new Exception(" the index of number is out out bound, it must be between 0 and "+Helper.visitorsNum);
		}
		visitior = Helper.vistors[num];
		return visitior;
	}
	
	/**
	 * get a certain location which is selected by a random number generated by RandomGenerator
	 * @param generator
	 * @return
	 * @throws Exception
	 */
	public Location getLocation(RandomGenerator generator) throws Exception{
		Location location = null;
		int num = generator.getLocationRandom();
		if(num >= Helper.visitorsNum){
			throw new Exception(" the index of number is out out bound, it must be between 0 and "+Helper.locationsNum);
		}
		location = Helper.locations[num];
		return location;
	}
	
	
}
